name: Gitinfo Lua CI/CD

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          path: gitinfo-lua
          fetch-tags: true
          fetch-depth: 0
      - name: Add git directories
        run: git config --global --add safe.directory $PWD/*
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: maclotsen/xerdi-latex:ctantl
            shell: bash
            options: --rm -i -v ${{ github.workspace }}:/data
            run: make -C gitinfo-lua build
      - name: Upload Documentation
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/gitinfo-lua/doc
