name: Build Docs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build git-latex.tex
      uses: dante-ev/latex-action@latest
      with:
        root_file: clean
        args: build
        compiler: make
